fix(CI/I): Remove the image docker

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -28,8 +28,10 @@ jobs:
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
-      - name: List Files
-        run: ls -la
+
+      - name: Remove old Docker image
+        run: |
+          docker rmi -f misterfacile/fastapi-app:latest || echo "Image not found"
   
       - name: SSH to Server and Deploy
         uses: appleboy/scp-action@master
@@ -41,7 +43,6 @@ jobs:
             target: "/home/ubuntu/paul.guan"
             debug: true
 
-            
       - name: SSH Command to Restart Service
         uses: appleboy/ssh-action@master
         with:
